export const MODEL_MANIFEST = {
  "anglerfish": { file: "Anglerfish.fbx", name: "Anglerfish", price: 140, color: 0x66bbcc, rot: [0, 0, 0] },
  "armoredcatfish": { file: "ArmoredCatfish.fbx", name: "Armored Catfish", price: 70, color: 0x66bbcc, rot: [0, 0, 0] },
  "betta": { file: "Betta.fbx", name: "Betta", price: 90, color: 0x66bbcc, rot: [0, 0, 0] },
  "blacklionfish": { file: "BlackLionFish.fbx", name: "Black Lion Fish", price: 40, color: 0x66bbcc, rot: [0, 0, 0] },
  "blobfish": { file: "Blobfish.fbx", name: "Blobfish", price: 140, color: 0x66bbcc, rot: [0, 0, 0] },
  "bluegoldfish": { file: "BlueGoldfish.fbx", name: "Blue Goldfish", price: 90, color: 0x66bbcc, rot: [0, 0, 0] },
  "bluetang": { file: "BlueTang.fbx", name: "Blue Tang", price: 110, color: 0x66bbcc, rot: [0, 0, 0] },
  "butterflyfish": { file: "ButterflyFish.fbx", name: "Butterfly Fish", price: 120, color: 0x66bbcc, rot: [0, 0, 0] },
  "cardinalfish": { file: "CardinalFish.fbx", name: "Cardinal Fish", price: 30, color: 0x66bbcc, rot: [0, 0, 0] },
  "clownfish": { file: "Clownfish.fbx", name: "Clownfish", price: 100, color: 0x66bbcc, rot: [0, 0, 0] },
  "coralgrouper": { file: "CoralGrouper.fbx", name: "Coral Grouper", price: 100, color: 0x66bbcc, rot: [0, 0, 0] },
  "cowfish": { file: "Cowfish.fbx", name: "Cowfish", price: 140, color: 0x66bbcc, rot: [0, 0, 0] },
  "flowerhorn": { file: "FlowerHorn.fbx", name: "Flower Horn", price: 90, color: 0x66bbcc, rot: [0, 0, 0] },
  "goblinshark": { file: "GoblinShark.fbx", name: "Goblin Shark", price: 90, color: 0x66bbcc, rot: [0, 0, 0] },
  "goldfish": { file: "Goldfish.fbx", name: "Goldfish", price: 30, color: 0x66bbcc, rot: [0, 0, 0] },
  "guppyfish": { file: "guppy_fish.glb", name: "Guppy", price: 140, color: 0x66bbcc, rot: [0, 0, 0] },
  "guppyfish1": { file: "guppy_fish_1.glb", name: "Guppy 1", price: 50, color: 0x66bbcc, rot: [0, 0, 0] },
  "guppyfish2": { file: "guppy_fish_2.glb", name: "Guppy 2", price: 60, color: 0x66bbcc, rot: [0, 0, 0] },
  "humphead": { file: "Humphead.fbx", name: "Humphead", price: 30, color: 0x66bbcc, rot: [0, 0, 0] },
  "koi": { file: "Koi.fbx", name: "Koi", price: 80, color: 0x66bbcc, rot: [0, 0, 0] },
  "lionfish": { file: "Lionfish.fbx", name: "Lionfish", price: 110, color: 0x66bbcc, rot: [0, 0, 0] },
  "mandarinfish": { file: "MandarinFish.fbx", name: "Mandarin Fish", price: 70, color: 0x66bbcc, rot: [0, 0, 0] },
  "moorishidol": { file: "MoorishIdol.fbx", name: "Moorish Idol", price: 80, color: 0x66bbcc, rot: [0, 0, 0] },
  "parrotfish": { file: "ParrotFish.fbx", name: "Parrot Fish", price: 130, color: 0x66bbcc, rot: [0, 0, 0] },
  "piranha": { file: "Piranha.fbx", name: "Piranha", price: 80, color: 0x66bbcc, rot: [0, 0, 0] },
  "puffer": { file: "Puffer.fbx", name: "Puffer", price: 130, color: 0x66bbcc, rot: [0, 0, 0] },
  "redsnapper": { file: "RedSnapper.fbx", name: "Red Snapper", price: 130, color: 0x66bbcc, rot: [0, 0, 0] },
  "royalgramma": { file: "RoyalGramma.fbx", name: "Royal Gramma", price: 130, color: 0x66bbcc, rot: [0, 0, 0] },
  "shark": { file: "Shark.fbx", name: "Shark", price: 120, color: 0x66bbcc, rot: [0, 0, 0] },
  "swordfish": { file: "Swordfish.fbx", name: "Swordfish", price: 60, color: 0x66bbcc, rot: [0, 0, 0] },
  "tang": { file: "Tang.fbx", name: "Tang", price: 90, color: 0x66bbcc, rot: [0, 0, 0] },
  "tetra": { file: "Tetra.fbx", name: "Tetra", price: 130, color: 0x66bbcc, rot: [0, 0, 0] },
  "tuna": { file: "Tuna.fbx", name: "Tuna", price: 110, color: 0x66bbcc, rot: [0, 0, 0] },
  "yellowtang": { file: "YellowTang.fbx", name: "Yellow Tang", price: 130, color: 0x66bbcc, rot: [0, 0, 0] },
  "zebraclownfish": { file: "ZebraClownFish.fbx", name: "Zebra Clown Fish", price: 140, color: 0x66bbcc, rot: [0, 0, 0] },
}
